// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbe-5cfxPDeRyMD5yOREHbD3KK_ZCOJCw',
    appId: '1:36881891765:web:8fee24820daada5cc399fc',
    messagingSenderId: '36881891765',
    projectId: 'project-e-cc696',
    authDomain: 'project-e-cc696.firebaseapp.com',
    storageBucket: 'project-e-cc696.firebasestorage.app',
    measurementId: 'G-YQME8N1CD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgJfg5zNEv-ewFpuQCwrbDDjqAHxoTaw4',
    appId: '1:36881891765:android:1e2a55b4feb51bbfc399fc',
    messagingSenderId: '36881891765',
    projectId: 'project-e-cc696',
    storageBucket: 'project-e-cc696.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU4Ps666qynx3xTmI4_EqaTHH9hPe3AE4',
    appId: '1:36881891765:ios:16ccdda2f3d6a81ec399fc',
    messagingSenderId: '36881891765',
    projectId: 'project-e-cc696',
    storageBucket: 'project-e-cc696.firebasestorage.app',
    iosBundleId: 'com.example.vjdProjectfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU4Ps666qynx3xTmI4_EqaTHH9hPe3AE4',
    appId: '1:36881891765:ios:16ccdda2f3d6a81ec399fc',
    messagingSenderId: '36881891765',
    projectId: 'project-e-cc696',
    storageBucket: 'project-e-cc696.firebasestorage.app',
    iosBundleId: 'com.example.vjdProjectfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbe-5cfxPDeRyMD5yOREHbD3KK_ZCOJCw',
    appId: '1:36881891765:web:48ffbda089021b4fc399fc',
    messagingSenderId: '36881891765',
    projectId: 'project-e-cc696',
    authDomain: 'project-e-cc696.firebaseapp.com',
    storageBucket: 'project-e-cc696.firebasestorage.app',
    measurementId: 'G-25F9DPEFXJ',
  );
}
